### ISSUE TITLE
unable to locally tests transform-jsx within framework

### ISSUE THREAD

**Issue by Cmdv** [calebmer/node_modules#1]
Hi @calebmer 

I'm now struggling to get things set up for local testing of the constructor function.

```Js
/* package.json */
"babel": {
    "env": {
      "test": {
        "plugins": [["transform-jsx", { "function": "jsx" }]]
      }
    }
  },
"scripts": {
    "pretest-browser": "BABEL_ENV=test browserify test/browser/index.js -t babelify -o test/browser/page/tests-bundle.js"
}
```
I tried other imaginable combinations like `"function": "./jsx"` + `"module": "jsx"`.
but I get:
`TypeError: The plugin ["transform-jsx",{"function":"jsx"}] didn't export a Plugin instance while parsing file: /cycle-dom/test/browser/index.js
`

do you have any recommendation how I can approach testing that `babel-plugin-transform-jsx` construction function is in fact working?

Thanks :)

**Comment by calebmer** [comment]
When you only use `function` you must manually import/require the function like in React. So if you wrote `"function": "myFunFunction"` a function with the name `myFunFunction` must be defined somewhere in the file. That's what is recommend for tests.

Another option is to use `"module": "../../jsx"` (I'm guessing your file path) where the path is relative to the test file.

**Comment by Cmdv** [comment]
:( thanks tried this and still no luck!

not sure if you can spot what is going wrong!! 
https://github.com/Cmdv/cycle-dom/blob/transform-jsx/package.json

I've just put it under another branch but can't get it to play ball

**Comment by calebmer** [comment]
`function` is for the function name, `module` is for the file name 😊

You'll want to use `module` as the key.

Check out the [examples](https://github.com/calebmer/node_modules/tree/master/packages/babel-plugin-transform-jsx) for a visual representation.

**Comment by Cmdv** [comment]
also tried that exactly the same error and as many variations of file location but just won't pull it in!! really wierd bet it's something dead simple. I'll close this and keep digging thank for the help though :+1:

**Comment by calebmer** [comment]
Ok, if you want I can write the test in ~3 days.

**Comment by Cmdv** [comment]
@calebmer were you still up for helping with tests? thanks :)

**Comment by calebmer** [comment]
Of course, I'm sorry I forgot I made that commitment 😊

Give me the up to date link and I'll jump on it ASAP.

**Comment by Cmdv** [comment]
It's ok so did I, just happened to find it as we rearranged all our issues today, but it;s in the same branch and location as mentioned before:

[package.json](https://github.com/Cmdv/cycle-dom/blob/transform-jsx/package.json) + [render.js test](https://github.com/Cmdv/cycle-dom/blob/transform-jsx/test/browser/render.js)

and the last recommendation from André on this [PR](https://github.com/cyclejs/dom/pull/93/files) was:
> check in tests/browser/render.js there is a test for JSX using hJSX. It's enough to make a test file that imports this jsx file, creates some JSX of some divs, then inspects what is the output. The npm pretest-browser script uses babelify to transpile the tests, so maybe you can point to a test babel configuration that will then specify the plugins.

which I tried all sorts of experimentations but to no avail :(

**Comment by calebmer** [comment]
👍

I'll help with issues in the PR now.
